config/routes.rb
Rails.application.routes.draw do

  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout}, controllers: { sessions: 'users/sessions' }

  resources :tests, only: :index do
    member do
      post :start, to: "tests#start"
    end
  end

  resources :badges, only: :index

  resources :test_passages, only: %i[show update] do
    resources :gist, param: :test_passage_id, only: :create
    member do
      get :result
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gist, only: :index
    resources :badges
  end
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :user_badges
  has_many :users, through: :user_badges

  validates :title, presence: true
  validates :condition, presence: true
  validates :option, presence: true
  validates :img, presence: true
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController
  before_action :set_badge, only: %i[ show edit update destroy ]

  def index
    @badges = Badge.all
  end

  def show
  end

  def new
    @badge = Badge.new
  end

  def edit
  end

  def create
    @badge = Badge.new(badge_params)

    if @badge.save
      redirect_to admin_badges_path(@badge)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @badge.update(badge_params)
      redirect_to admin_badges_path(@badge)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @badge.destroy
    redirect_to admin_badges_path
  end

  private
    def set_badge
      @badge = Badge.find(params[:id])
    end

    def badge_params
      params.require(:badge).permit(:title, :img, :condition, :option)
    end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  def index
    @all_badges = Badge.all
    @user_badges = current_user.badges
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/views/admin/badges/_badge.html.erb
<tr>
  <td><%= badge.title %></td>
  <td><%= image_tag(badge.img) %></td>
  <td><%= badge.condition %></td>
  <td><%= badge.option %></td>
  <td><%= link_to t('show'), admin_badge_path(badge) %></td>
  <td><%= link_to t('edit'), edit_admin_badge_path(badge) %></td>
  <td><%= link_to t('delete'), admin_badge_path(badge), method: :delete, data: { confirm: t('are_you_sure?') } %></td>
</tr>

app/views/admin/badges/_form.html.erb
<%= form_with(model: [:admin, badge], local: true) do |form| %>
  <%= render 'shared/errors', resource: badge %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :img_source %>
    <%= form.text_field :img %>
  </div>

  <p>
    <%= form.label :condition %>
    <%= form.select :condition, BadgeService::CONDITIONS.keys%>
  </p>

  <div class="field">
    <%= t("options").html_safe %>
    <%= form.text_field :option %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/badges/edit.html.erb
<h1><%= t('Editing Badge') %></h1>

<%= render 'form', badge: @badge %>

<%= link_to t('show'), admin_badge_path(@badge) %> |
<%= link_to t('back'), admin_badges_path %>

app/views/admin/badges/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t('badges') %></h1>

<table>
  <th> <%= t('title') %> </th>
  <th> <%= t('image') %> </th>
  <th> <%= t('condition') %> </th>
  <th> <%= t('option') %> </th>
  <th colspan="3"> <%= t('action') %> </th>
  <%= render @badges %>
</table>

<br>

<%= link_to 'New Badge', new_admin_badge_path %>

app/views/admin/badges/new.html.erb
<h1><%= t('new badge') %></h1>

<%= render 'form', badge: @badge %>

<%= link_to 'Back', admin_badges_path %>

app/views/admin/badges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= t('title') %> </strong>
  <%= @badge.title %>
</p>

<p>
  <strong><%= t('image') %> </strong>
  <%= image_tag(@badge.img) %>
</p>

<p>
  <strong><%= t('condition') %> </strong>
  <%= @badge.condition %>
</p>

<p>
  <strong><%= t('option') %> </strong>
  <%= @badge.option %>
</p>

<%= link_to t('edit'), edit_admin_badge_path(@badge) %> |
<%= link_to t('back'), admin_badges_path %>