config/routes.rb
Rails.application.routes.draw do

  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout}, controllers: { sessions: 'users/sessions' }

  resources :tests, only: :index do
    member do
      post :start, to: "tests#start"
    end
  end

  resources :badges, only: :index

  resources :test_passages, only: %i[show update] do
    resources :gist, param: :test_passage_id, only: :create
    member do
      get :result
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gist, only: :index
    resources :badges
  end
end

app/models/admin.rb
class Admin < User
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :title, presence: true
  validate :validate_number_of_answers, on: :create

  scope :all_correct, -> { where(correct: true) }

  private

  def validate_number_of_answers
    errors.add(:base) if question.answers.size >= 4
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :user_badges
  has_many :users, through: :user_badges

  validates :title, presence: true
  validates :condition, presence: true
  validates :option, presence: true
  validates :img, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  default_scope { order(:title) }

  has_many :tests, dependent: :destroy

  validates :title, presence: true
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy

  validates :title, presence: true
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'user_id'
  belongs_to :category
  has_many :questions, dependent: :destroy
  has_many :test_passages, dependent: :destroy
  has_many :users, through: :test_passages

  validates :time_limit_in_minutes, presence: true
  validates :title, uniqueness: { scope: :level }
  validates :title, presence: true
  validates :level, presence: true,
                    numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  scope :easy, -> { where(level: 0..1) }
  scope :medium, -> { where(level: 2..4) }
  scope :hard, -> { where(level: 5..Float::INFINITY) }
  scope :tests_by_category, ->(category) { joins(:category).where(categories: { title: category }) }

  def self.titles_by_category(category)
    tests_by_category(category).order(title: :desc).pluck(:title)
  end
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  MIN_POINTS = 85

  before_validation :before_validation_set_first_question, on: :create
  before_validation :before_validation_next_question, on: :update

  def completed?
    current_question.nil? || time_is_up?
  end

  def time_is_up?
    self.created_at + self.test.time_limit_in_minutes * 60 - Time.current <= 0
  end

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)

    save!
  end

  def success?
    percent >= MIN_POINTS
  end

  def percent
    correct_questions.to_f / test.questions.count * 100.0
  end

  private

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort unless answer_ids.nil?
  end

  def correct_answers
    current_question.answers.all_correct
  end

  def before_validation_next_question
    self.current_question = test.questions.order(:id).where('id > ?', current_question.id).first
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable,
         :confirmable

  has_many :created_tests, class_name: 'Test', dependent: :destroy
  has_many :test_passages, dependent: :destroy
  has_many :tests, through: :test_passages
  has_many :user_badges
  has_many :badges, through: :user_badges

  validates :email, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :first_name, presence:  true
  validates :last_name, presence:  true

  def passed_tests_by_level(level)
    User.joins(:tests).where(tests: { level: level }, test_passages: { user: id })
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end
end

app/models/user_badge.rb
class UserBadge < ApplicationRecord
  belongs_to :user
  belongs_to :badge
end

app/controllers/gist_controller.rb
class GistController < ApplicationController
  def create
    @test_passage = TestPassage.find(params[:test_passage_id])
    @result = GistQuestionService.new(@test_passage.current_question).call

    if @result.success?
      flash[:notice] =  t("gist_flash", url: @result.url, question_title: @test_passage.current_question.title)
      Gist.create!(gist_url: @result.url, user: current_user, question: @test_passage.current_question)
    else
      flash[:alert] = t("failure")
    end

    redirect_to @test_passage
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  def index
    @tests = Test.all
  end

  def start
    @test = Test.find(params[:id])
    current_user.tests.push(@test)
    redirect_to current_user.test_passage(@test)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_year
    Time.current.year
  end

  def github_url(author, repo)
    link_to 'Github', "http://github.com/#{author}/#{repo}", target: :_blank
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/gist_helper.rb
module GistHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    "#{question.new_record? ? t('create_new') : t('edit') } #{question.test.title} #{ t('question') }"
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
  def result(test_passage)
    if test_passage.success?
      t("t_passed", percent: test_passage.percent.round)
    else
      t("t_not_passed", percent: test_passage.percent.round)
    end
  end

  def time(test_passage)
    if test_passage.created_at + test_passage.test.time_limit_in_minutes * 60 - Time.current > 0
      test_passage.created_at + test_passage.test.time_limit_in_minutes * 60 - Time.current
    end
  end

  def test_progress(test_passage)
    "#{(test_passage.current_question.id.to_i - test_passage.test.questions.first.id.to_i) / test_passage.test.questions.size.to_f * 100}".to_f.round
  end
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/admin/_nav.html.erb
<div class="nav nav-admin">
  <span class="nav-admin title">TestGuru Admin Panel</span>

  <div class="nav-admin user">
    Welcome, <%= current_user.first_name %> Guru |
    <%= link_to 'TestGuru', admin_tests_path %> |
    <%= link_to t("gist.index.gists"), admin_gist_index_path %> |
    <%= link_to t("badges"), admin_badges_path %> |
    <%= link_to t('logout'), destroy_user_session_path, method: :delete %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <p><%= t('author') %>: <%= render html: github_url('utgak', 'TestGuru') %>
  </p>

  <p>
    <%= t('ed_prj') %> <%= link_to 'Thinknetica', 'http://thinknetica.com', target: :_blank %>
  </p>
  <p> <%= t('year') %>: <%= current_year %></p>
</footer>

app/views/layouts/_navigation.html.erb
<% if user_signed_in? %>
  <p class="nav user">
    <%= t('welcome') %>, <b><%= current_user.first_name %></b> Guru |
    <%= link_to 'TestGuru', root_path %> |
    <%= link_to t('badges'), badges_path %> |
    <%= link_to t('logout'), destroy_user_session_path, method: :delete %>
  </p>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin Panel | TestGuru</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'admin/nav' %>
    <%= render 'shared/flash' %>

    <%= yield %>
  </body>
  <%= render 'layouts/footer' %>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestGuru</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navigation' %>
    <%= yield %>
  </body>
  <%= render 'layouts/footer' %>
</html>

app/views/shared/_errors.erb
<% if resource.present? and resource.errors.any? %>
  <%= content_tag :div, class: 'resource-errors', data: { resource_id: resource.id } do %>
    <h2><%= pluralize(resource.errors.count, 'error') %> detected:</h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
  <%= content_tag :div, message.html_safe, class: "flash #{key}" %>
<% end %>